steps:
- name: 'bash'
  args:
  - '-c'
  - |
    echo "MIDTRANS_SERVER_KEY=$$SERVER_KEY" > .env
    echo "MIDTRANS_CLIENT_KEY=$$CLIENT_KEY" >> .env
    echo "MIDTRANS_IS_PRODUCTION=false" >> .env
  secretEnv: ['SERVER_KEY', 'CLIENT_KEY']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['app', 'deploy']
  timeout: '1600s'

availableSecrets:
  secretManager:
  - versionName: projects/warnu-new/secrets/midtrans-server-key/versions/latest
    env: 'SERVER_KEY'
  - versionName: projects/warnu-new/secrets/midtrans-client-key/versions/latest
    env: 'CLIENT_KEY'

options:
  logging: CLOUD_LOGGING_ONLY