# cloudbuild.yaml (Versi Final dengan Perbaikan Logging)

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'app',
    'deploy',
    '--set-env-vars',
    'MIDTRANS_SERVER_KEY=$$SERVER_KEY,MIDTRANS_CLIENT_KEY=$$CLIENT_KEY,MIDTRANS_IS_PRODUCTION=false'
  ]
  secretEnv: ['SERVER_KEY', 'CLIENT_KEY']
  timeout: '1600s'

availableSecrets:
  secretManager:
  - versionName: projects/NAMA-PROJECT-ANDA/secrets/midtrans-server-key/versions/latest
    env: 'SERVER_KEY'
  - versionName: projects/NAMA-PROJECT-ANDA/secrets/midtrans-client-key/versions/latest
    env: 'CLIENT_KEY'

# -- TAMBAHKAN 2 BARIS INI DI PALING BAWAH --
options:
  logging: CLOUD_LOGGING_ONLY