# cloudbuild.yaml (Kembali ke Versi Final yang Benar)

steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'app'
  - 'deploy'
  - '--set-env-vars'
  - 'MIDTRANS_SERVER_KEY=$$SERVER_KEY,MIDTRANS_CLIENT_KEY=$$CLIENT_KEY,MIDTRANS_IS_PRODUCTION=false'
  secretEnv: ['SERVER_KEY', 'CLIENT_KEY']
  timeout: '1600s'

availableSecrets:
  secretManager:
  - versionName: projects/warnu-f1434/secrets/midtrans-server-key/versions/latest
    env: 'SERVER_KEY'
  - versionName: projects/warnu-f1434/secrets/midtrans-client-key/versions/latest
    env: 'CLIENT_KEY'

options:
  logging: CLOUD_LOGGING_ONLY