# cloudbuild.yaml (Metode File Konfigurasi)

steps:
# Langkah 1: Buat file env.yaml yang berisi environment variables
- name: 'bash'
  args:
  - '-c'
  - |
    echo "env_variables:" > env.yaml
    echo "  MIDTRANS_SERVER_KEY: '$$SERVER_KEY'" >> env.yaml
    echo "  MIDTRANS_CLIENT_KEY: '$$CLIENT_KEY'" >> env.yaml
    echo "  MIDTRANS_IS_PRODUCTION: 'false'" >> env.yaml
  secretEnv: ['SERVER_KEY', 'CLIENT_KEY']

# Langkah 2: Deploy aplikasi dengan menggabungkan app.yaml dan env.yaml
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'app'
  - 'deploy'
  - 'app.yaml' # Deploy app.yaml utama
  - 'env.yaml' # Gabungkan dengan env.yaml yang baru dibuat
  timeout: '1600s'

availableSecrets:
  secretManager:
  - versionName: projects/warnu-f1434/secrets/midtrans-server-key/versions/latest
    env: 'SERVER_KEY'
  - versionName: projects/warnu-f1434/secrets/midtrans-client-key/versions/latest
    env: 'CLIENT_KEY'

options:
  logging: CLOUD_LOGGING_ONLY