# cloudbuild.yaml (Metode Final: Membuat .env Secara Aman)

steps:
# Langkah 1: Ambil secret dan tulis ke dalam file .env
# File ini akan dibuat di dalam lingkungan build dan ikut di-deploy bersama aplikasi.
# File ini TIDAK AKAN PERNAH ada di repositori GitHub Anda.
- name: 'bash'
  args:
  - '-c'
  - |
    echo "MIDTRANS_SERVER_KEY=$$SERVER_KEY" > .env
    echo "MIDTRANS_CLIENT_KEY=$$CLIENT_KEY" >> .env
    echo "MIDTRANS_IS_PRODUCTION=false" >> .env
  secretEnv: ['SERVER_KEY', 'CLIENT_KEY']

# Langkah 2: Deploy aplikasi.
# File .env yang dibuat di langkah sebelumnya akan ikut ter-deploy bersama kode lainnya.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['app', 'deploy']
  timeout: '1600s'

# Bagian ini tetap diperlukan untuk mengambil secret dari Secret Manager
availableSecrets:
  secretManager:
  - versionName: projects/warnu-f1434/secrets/midtrans-server-key/versions/latest
    env: 'SERVER_KEY'
  - versionName: projects/warnu-f1434/secrets/midtrans-client-key/versions/latest
    env: 'CLIENT_KEY'

options:
  logging: CLOUD_LOGGING_ONLY