# cloudbuild.yaml (Versi Debugging)

steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['app', 'deploy']
  timeout: '1600s'

options:
  logging: CLOUD_LOGGING_ONLY